apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummycd-server
  namespace: operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummycd-server
  template:
    metadata:
      labels:
        app: dummycd-server
    spec:
      volumes:
        - name: dummycd-server-configmap-volume
          configMap:
            name: dummycd-server-configmap
        - name: dummycd-server-storage-volume
          emptyDir: {}
      containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
          args:
            - '--secure-listen-address=0.0.0.0:8443'
            - '--upstream=http://127.0.0.1:8080/'
            - '--logtostderr=true'
            - '--v=0'
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
        - name: server
          image: yimgzz/dummycd-server:0.0.1
          command:
            - /dummycd
          args:
            - '--log-level=debug'
          volumeMounts:
            - mountPath: /home/nonroot/.ssh/knownhosts
              name: dummycd-server-configmap-volume
              subPath: knownhosts
            - name: dummycd-server-storage-volume
              mountPath: /home/nonroot/.dummycd
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      serviceAccountName: operator-controller-manager
      serviceAccount: operator-controller-manager
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
