---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dummy.cd
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dummy.cd
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - dummy.cd
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dummy.cd
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dummy.cd
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - dummy.cd
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
